DELETE FROM STOCK;
INSERT INTO warehouse.STOCK(GOODS_CODE, QUANTITY, STATUS) VALUES(100, 10, 'ACTIVE');
INSERT INTO warehouse.STOCK(GOODS_CODE, QUANTITY, STATUS) VALUES(200, 5, 'ACTIVE');
INSERT INTO warehouse.STOCK(GOODS_CODE, QUANTITY, STATUS) VALUES(400, 0, 'ACTIVE');
INSERT INTO warehouse.STOCK(GOODS_CODE, QUANTITY, STATUS) VALUES(500, 0, 'DEACTIVE');
INSERT INTO warehouse.STOCK(GOODS_CODE, QUANTITY, STATUS) VALUES(700, 0, 'ACTIVE');
INSERT INTO warehouse.STOCK(GOODS_CODE, QUANTITY, STATUS) VALUES(800, 0, 'DEACTIVE');